spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zalord
    username: postgres
    password: user
  jpa:
    hibernate:
      # This must be 'update' instead of 'validate' so Hibernate can build the event table 
      # for modolith checker automatically
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api/v1